### ISSUE TITLE
Implement bash pattern matching

### ISSUE THREAD

**Issue by bradrydzewski** [drone/envsubst#1]
Implement pattern matching for the following functions

    ${var#substring}
    ${var##substring}
    ${var%substring}
    ${var%%substring}
    ${var/substring/replacement}
    ${var//substring/replacement}
    ${var/#substring/replacement}
    ${var/%substring/replacement}

Based on the following specification:
http://wiki.bash-hackers.org/syntax/pattern
http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_13

Resources:
https://research.swtch.com/glob
https://play.golang.org/p/C-rYgJihRT

Conversion from Pattern string to Go Regexp:
https://github.com/mvdan/sh/blob/master/syntax/pattern.go#L45
https://github.com/mvdan/sh/blob/master/expand/param.go#L267

**Comment by bradrydzewski** [comment]
https://github.com/drone/envsubst/pull/5 implements a subset of pattern matching for `# ## % %%` using `path.Match` in the go standard library. This isn't a fully compliant implementation, but should definitely satisfy the majority of real world use cases (thanks @jmccann)

**Comment by jmccann** [comment]
@bradrydzewski Feel free to add some more commented tests of stuff that should work but doesn't.  I wouldn't mind maybe taking a further look into this later.  :)

**Comment by bradrydzewski** [comment]
possible alternative implementation that converts the pattern to a regex. need to explore further:
https://github.com/mvdan/sh/blob/master/syntax/pattern.go#L45
https://github.com/mvdan/sh/blob/master/expand/param.go#L267

**Comment by tphoney** [comment]
closing this as we are closing issues
