### ISSUE TITLE
toSubstr function should not return empty string when length exceeds

### ISSUE THREAD

**Issue by abc225666** [drone/envsubst#11]
https://github.com/drone/envsubst/blob/27180b1b92b7b062a132b1d25c64e5bf98cb40f9/funcs.go#L91-L95
I think this action is confusing, i met this problem in drone. When I set a variable ${env:0:8}, and if the length of variable "env" is less and equal to 8, it will be set to "".
If you define that when substitute length exceed should return empty string, I think that ok. But the length equals to should return that string.

example:
If var is 12345678, the result of ${var:0:8} is "", and if var is 123456789, the result is 12345678.
I think if var is 123456, then result of ${var:0:8} should be 123456, not ""

**Comment by tboerger** [comment]
I have prepared the PR https://github.com/drone/envsubst/pull/12 which also includes a unit test to keep this issue resolved in the future.
