### ISSUE TITLE
Please provide a better error message than "bad substitution"

### ISSUE THREAD

**Issue by asbjornu** [drone/envsubst#14]
First, thanks for creating this awesome tool! It is, however, a bit hard to use in practice since the only thing it outputs when an error occurs is `Bad substitution`. Would it be possible to output a bit more (contextual) information on what the precise problem is? A print of the line of input that caused the error would be very helpful, for instance.

**Comment by bradrydzewski** [comment]
sure, please consider sending a patch.

**Comment by tphoney** [comment]
A patch would be welcome 👍
