### ISSUE TITLE
Support ${var:-$othervar} syntax

### ISSUE THREAD

**Issue by CecileRobertMichon** [drone/envsubst#21]
It'd be great to be able to pass another var as part of the default.

Eg.

`${NAME:-id$ID}` would evaluate to `id123` where $NAME is not set and $ID is `123`.

Would be willing to help implement this if there is interest from others and you all think it'd be useful.

cc @wfernandes

**Comment by tboerger** [comment]
This would be useful, and if this is covered by tests I don't see any blocker.

**Comment by CecileRobertMichon** [comment]
Thanks @tboerger! Can you please review #23 ?
