### ISSUE TITLE
Escaping is happening outside of varaible substituion

### ISSUE THREAD

**Issue by jsturtevant** [drone/envsubst#26]
This library is used with Cluster API and I've run into an issue with escapes in https://github.com/kubernetes-sigs/cluster-api/issues/4016.  It is stripping backslashes when not used inside variable substitution.  I opened a PR (#27) that demonstrates it in a test.  

It seems the escape patterns are being processed across the whole file (more details in attached issue).  If I run `envsubt` command line tool I don't have the same issue:

```
curl -LO https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/kubeadm/kube-proxy/kube-proxy.yml
envsubst < kube-proxy.yml

#output truncated
   hostPath:
          path: \\.\pipe\rancher_wins 

```

Is this expected or a bug?

**Comment by wfernandes** [comment]
For reference, https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#unc-paths
