### ISSUE TITLE
Should envsubst ignore numeric variable names?

### ISSUE THREAD

**Issue by rfratto** [drone/envsubst#30]
The envsubst from GNU gettext ignores patterns with numbers in it:

```
$ echo "${USER} ${1}" 
robert 
$ echo '${USER} ${1}' | envsubst 
robert ${1}
```

Should this be the case for drone/envsubst too? I've been tripped up by this a few times as I use envsubst to replace environment variables in a file that also has regex capture group references, which are formatted as `${1}`. I temporarily hacked around this with grafana/agent#754, but it would be nice to ignore any pattern where the variable is just a number. 

This suggestion might be a little contentious; I know it drifts from the bash behavior.  I'm just not sure _why_ bash will substitute environment variables that are numbers, since as far as I can tell a number is never a valid identifier for a variable.

**Comment by tphoney** [comment]
Hey @rfratto i think a pr with an example unit test would better show this behaviour. but we are unlikely to merge changes that drift from current expected behaviour.
